mnc_blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):

    title=StringField('Title',validators=[DataRequired()])
    text=TextAreaField('Text',validators=[DataRequired()])
    submit=SubmitField('Post')

mnc_blog/blog_posts/views.py
from flask import render_template,redirect,flash,url_for,Blueprint,request
from mnc_blog import db
from mnc_blog.models import BlogPost
from flask_login import current_user,login_required
from mnc_blog.blog_posts.forms import BlogPostForm

blog_posts=Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create():

    form=BlogPostForm()

    if form.validate_on_submit():
        blog_post=BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        return redirect(url_for('core.index'))
    return render_template('create_post.html',form=form)

@blog_posts.route('/<int:blog_post_id>')
def read(blog_post_id):
    blog=BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog.title,date=blog.date,post=blog)

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog=BlogPost.query.get_or_404(blog_post_id)

    if blog.author != current_user:
        abort(403)

    form=BlogPostForm()

    if form.validate_on_submit():

        blog.title=form.title.data
        blog.text=form.text.data
        db.session.commit()
        return redirect(url_for('blog_posts.read',blog_post_id=blog_post_id))

    elif request.method=="GET":
        form.title.data=blog.title
        form.text.data=blog.text

    return render_template('create_post.html',title="Updating",form=form)

@blog_posts.route('/<int:blog_post_id>/delete',methods=['POST'])
@login_required
def delete(blog_post_id):
    blog=BlogPost.query.get_or_404(blog_post_id)

    if blog.author != current_user:
        abort(403)

    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('core.index'))

mnc_blog/core/views.py
from flask import render_template,request,Blueprint
from mnc_blog.models import BlogPost

core=Blueprint('core',__name__)

@core.route('/')
def index():
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

mnc_blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user,logout_user,current_user,login_required
from mnc_blog import db
from mnc_blog.users.forms import LoginForm, RegisterForm, UpdateUserForm
from mnc_blog.models import User, BlogPost
from mnc_blog.users.pic_handler import add_profile_pic

users=Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():

    form=RegisterForm()

    if form.validate_on_submit():
        user=User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Thanks for Registration!")
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        user=User.query.filter_by(email=form.email.data).first()

        if (user.check_password(form.password.data)) and (user is not None):

            login_user(user)
            flash('Login Successfull')

            next=request.args.get('next')

            if next==None or not next[0]=='/':
                next=url_for('core.index')

            return redirect(next)
    
    return render_template('login.html',form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@users.route('/accounts',methods=['GET','POST'])
@login_required
def accounts():

    form=UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username=current_user.username
            pic=add_profile_pic(form.picture.data,username)
            current_user.profile_image=pic
        
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash("Updated Successfully!")
        return redirect(url_for('users.accounts'))

    elif request.method=="GET":
        form.username.data=current_user.username
        form.email.data=current_user.email

    profile_image=url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('accounts.html',profile_image=profile_image,form=form)

@users.route('/<username>')
def user_posts(username):

    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    blog_posts=BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

mnc_blog/templates/accounts.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <div align="center">
        <h3>Welcome {{current_user.username}}!</h3>
        <img align="center" src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}" alt="">
    </div>
</div>

<div class="container">
    <div>
        <form method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            {{form.email.label}}{{form.email}}
            {{form.username.label}}{{form.username}}
            {{form.picture.label}}{{form.picture}}
            {{form.submit()}}
        </form>
    </div>
    
</div>

{% endblock %}

mnc_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="nav">
        <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
        <a class="nav-link" href="{{url_for('core.info')}}">About Us</a>
        
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
        <a class="nav-link" href="{{url_for('users.accounts')}}">Account</a>
        <a class="nav-link" href="{{url_for('blog_posts.create')}}">Create Post</a>
        {% else %}
        <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
        {% endif %}
      </nav>
    <div class="container">
        {% block content %}


        {% endblock %}

    </div>
</body>
</html>

mnc_blog/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <h2>{{title}}</h2>
    <h3>Written By: {{post.author}}</h3>
    <h4>Published: {{date.strftime('%B %d, %Y')}}</h4>
    <p>{{post.text}}</p>

    {% if post.author == current_user %}
    <div>
        <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#del_modal">
          Delete
        </button>
    </div>
    {% endif %}
</div>

<div class="modal" tabindex="-1" id="del_modal" aria-labelledby="del_modal_label">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="del_modal_label">Do you want to delete this post?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Once deleted, the post can't be retrieved.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        
        <form action="{{url_for('blog_posts.delete',blog_post_id=post.id)}}"  method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">

        </form>
      
      </div>
    </div>
  </div>
</div>

{% endblock %}

mnc_blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="POST">
        {{form.hidden_tag()}}
        {{form.title.label}}{{form.title}}
        <br>
        {{form.text.label}}
        {{form.text}}
        <br>
        {{form.submit()}}
    </form>

</div>


{% endblock %}

mnc_blog/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>MNC BLOG</h1>

</div>

<div class="container">
    {% for post in blog_posts.items %}
    <div class="card">
        <div class="card-body">
            <h2><a href="{{url_for('blog_posts.read',blog_post_id=post.id)}}">{{post.title}}</a></h2>
            <a href="{{url_for('users.user_posts',username=post.author.username)}}">Written By: {{post.author.username}}</a>
            <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
            <a href="{{url_for('blog_posts.read',blog_post_id=post.id)}}">Read</a>
        </div>

    </div>
    {% endfor %}
</div>
<nav aria-label='Page Navigation example'>
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
        {% if blog_posts.page == page_num %}
        <li class='page-item disabled'>
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{ page_num}}</a>
        </li>
        {% else %}
        <li class='page-item'>
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{ page_num}}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  
  </nav>


{% endblock %}

mnc_blog/templates/info.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>About Us</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima reprehenderit vitae recusandae at libero temporibus, culpa modi odit eaque quas, totam aliquam velit. Dicta, ducimus atque. Eveniet, assumenda! Eaque, voluptates.
        
    </p>

</div>



{% endblock %}

mnc_blog/templates/login.html
{% extends "base.html" %}

{% block content %}

<form method="POST">

    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}
    {{form.password.label}}{{form.password}}
    {{form.submit()}}

</form>


{% endblock %}

mnc_blog/templates/register.html
{% extends "base.html" %}

{% block content %}

<form method="POST">

    <div class="container">
        {{form.hidden_tag()}}
        {{form.email.label}}{{form.email}}
        <br>
        <br>
        {{form.username.label}}{{form.username}}
        <br>
        <br>
        {{form.password.label}}{{form.password}}
        <br>
        <br>
        {{form.conf_password.label}}{{form.conf_password}}
        <br>
        <br>
        {{form.submit()}}

</form>


{% endblock %}

mnc_blog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1>Welcome {{user.username}}!</h1>
      <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" >
    </div>
  </div>


{% for post in blog_posts.items  %}
  <h2> <a href="{{url_for('blog_posts.read',blog_post_id=post.id)}}">{{post.title}}</a> </h2>
  Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
  <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
   <br>
   <p>{{post.text}}</p>
   <br>
{% endfor %}
</div>

<nav aria-label='Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
      {% if blog_posts.page == page_num %}
      <li class='page-item disabled'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% else %}
      <li class='page-item'>
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>

</nav>




{% endblock %}